---
- name: Install Apache httpd and PHP and enable service
  hosts: test
  become: yes
  tasks:
   - name: Update the cache
     apt: 
      update_cache: yes

   - name: Install apache2
     apt: 
      name: apache2
      state: present

   - name: Install PHP
     apt: 
      name: php
      state: present

   - name: Start and Enable Apache2-Service
     service: 
      name: apache2
      state: started
      enabled: yes

   - name: Remove old default page from Apache installation
     file:
      path: /var/www/html/index.html
      state: absent

   - name: Copy default page to document root
     copy:
      src: index.php
      dest: /var/www/html/index.php
      owner: root
      group: root
      mode: u=rw,g=r,o=r

   - name: Copy style.css of default page to document root
     copy:
      src: style.css
      dest: /var/www/html/style.css
      owner: root
      group: root
      mode: u=rw,g=r,o=r

   - name: Autoclean
     apt:
      autoclean: yes

   - name: Autoremove
     apt:
      autoremove: yes
